### PR TITLE
Treasure567

### PR DESCRIPTION
**Pull request by treasure567**
All working according to project specifications.

### CODE REVIEW

**Review by ahmadinjo — COMMENTED** [review]
Why do you have "os", "http", and "fs" as dependencies?

**Comment by treasure567** [comment]
Removed. Only nodemon is a dev dependency.

**Comment by ahmadinjo** [comment]
> Removed. Only nodemon is a dev dependency.

Well done boss, I think it's good to go. Let's wait for team lead to confirm and merge

**Comment by treasure567** [comment]
Ok thanks.

**Pull request merged**
